---

bgp:
  as: "100"
  peers:
    - host: "10.19.20.20"
      remote_as: "20"
      update_source: ""
      next_hop_self: false
      address_families:
        - "ipv4"
    - host: "2.2.2.2"
      remote_as: "100"
      update_source: "loopback0"
      next_hop_self: true
      address_families:
        - "ipv4"

  networks: ""
  route_policy: ""