---

bgp:
  as: "200"
  retain_rt: true
  peers:
    - host: "20.20.20.20"
      remote_as: "200"
      update_source: "loopback0"
      next_hop_self: true
      route_reflector_client: true
      ebgp_multihop: true
      address_families:
        - "vpnv4"
    - host: "30.1.19.1"
      remote_as: "100"
      update_source: ""
      next_hop_self: false
      route_reflector_client: false
      ebgp_multihop: false
      address_families:
        - "vpnv4"        
  networks: ""
  route_policy: ""