---

bgp:
  as: "200"
  peers:
    - host: "20.20.20.20"
      remote_as: "200"
      update_source: "loopback0"
      next_hop_self: true
      route_reflector_client: true
      ebgp_multihop: true
      address_families:
        - "vpnv4"    
  networks: ""
  route_policy: ""