---

mpls:
  protocol: "ldp"
  router_id: "loopback0"
  interfaces:
    - intf: "g0/0/0/0"
    - intf: "g0/0/0/1"
  autoconfig:
    - igp: "ospf"
      process_id: "100"
      enable: False
    - igp: "isis"
      process_id: ""
      enable: True
  neighbors:
    - host: "5.5.5.5"
      authenticate: True
      password: "R5PASS"
  group_acl: ""
  option_1: ""
  fallback:
    password: "DEFAULTPASS"