---

ospf:
  process_id: "100"
  router_id: "19.19.19.19"
  interfaces:
    - intf: "g0/0/0/0"      
      area: "0"
      cost: ""
      network_type: "point-to-point"
      authentication_type: "md5"
      authentication_key: "INEMD5"
    - intf: "g0/0/0/1"
      area: "0"
      cost: "1000"
      network_type: ""
      authentication_type: "plaintext"
      authentication_key: "INECLEAR"
    - intf: "g0/0/0/2"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - intf: "loopback0"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""