---

l3vpns:
  - vrf: "VPN_B"
    rd: "100:2"
    address_families:
      - family: "ipv4"
        rt_import:
          - "100:2"
        rt_export:
          - "100:2"
    interfaces:
      - intf: "g0/0/0/2"
        ipv4_add: "10.19.20.19"
        mask: "24"
    routing:
      type: "eigrp"
      as: "1"
      metric: "10"
      networks:
        - subnet: "10.19.20.0"
          mask: "32"

          
