---

l3vpns:
  - vrf: "VPN_A"
    rd: "100:1"
    address_families:
      - family: "ipv4"
        rt_import: "100:1"
        rt_export: "100:1"
    interfaces:
      - intf: "g0/0/0/2"
        ipv4_add: "10.19.20.19"
        mask: "24"
    routing:
      type: "ospf"
      process: "100"
      metric: "128"
      networks:
        - subnet: "10.19.20.0"
          mask: "24"
          next_hop: ""
          
