---

l3vpns:
  - vrf: "VPN_D"
    rd: "100:4"
    address_families:
      - family: "ipv4"
        rt_import:
          - "100:7"
          - "100:8"
        rt_export:
          - "19.19.19.19:7"
          - "19.19.19.19:8"
    interfaces:
      - intf: "g0/0/0/2"
        ipv4_add: "10.19.20.19"
        mask: "24"
    routing:
      type: "static"
      metric: "10"
      networks:
        - subnet: "20.20.20.20"
          mask: "32"
          next_hop: "10.19.20.20"

          
