---

bgp:
  as: "100"
  peers:
    - host: "3.3.3.3"
      remote_as: "100"
      update_source: "loopback0"
      next_hop_self: true
      route_reflector_client: false
      address_families:
        - "vpnv4"
  networks: ""