---

l3vpns:
  # - vrf: "VPN_A"
  #   rd: "200:1"
  #   address_families:
  #     - family: "ipv4"
  #       rt_import:
  #         - "200:1"
  #       rt_export:
  #         - "200:1"
  #   interfaces:
  #     - intf: "g0/0/0/2"
  #       ipv4_add: "30.10.20.20"
  #       mask: "24"
  #   routing:
  #     type: "eigrp"
  #     as: "1"
  #     metric: "10"
  #     networks:
  #       - subnet: "30.10.20.0"
  #         mask: "24"
  - vrf: "VPN_B"
    rd: "200:2"
    address_families:
      - family: "ipv4"
        rt_import:
          - "200:2"
        rt_export:
          - "200:2"
    interfaces:
      - intf: "g0/0/0/1"
        ipv4_add: "40.8.20.20"
        mask: "24"
    routing:
      type: "eigrp"
      as: "1"
      metric: "10"
      networks:
        - subnet: "40.8.20.0"
          mask: "24"

          
