---

l3vpns:
  - vrf: "VPN_A"
    rd: "101:201"
    address_families:
      - family: "ipv4"
        rt_import:
          - "101:201"
        rt_export:
          - "101:201"
    interfaces:
      - intf: "g0/2"
        ipv4_add: "30.2.9.2"
        mask: "255.255.255.0"
    routing:
      type: "eigrp"
      as: "1"
      metric: "10"
      networks:
        - subnet: "30.2.9.0"
          mask: "0.0.0.255"
  # - vrf: "VPN_B"
  #   rd: "100:2"
  #   address_families:
  #     - family: "ipv4"
  #       rt_import:
  #         - "100:2"
  #       rt_export:
  #         - "100:2"
  #   interfaces:
  #     - intf: "g0/1"
  #       ipv4_add: "40.2.7.2"
  #       mask: "255.255.255.0"
  #   routing:
  #     type: "eigrp"
  #     as: "1"
  #     metric: "10"
  #     networks:
  #       - subnet: "40.2.7.0"
  #         mask: "0.0.0.255"

