---

ospf:
  process_id: "100"
  router_id: "3.3.3.3"
  networks:
    - subnet: "10.2.3.0"
      intf: "g0/0"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""   
    - subnet: "10.1.3.0"
      intf: "g0/2"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - subnet: "3.3.3.3"
      intf: "loopback0"
      mask: "0.0.0.0"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
  passive_interfaces:
    - intf: "loopback0"