---

interfaces:
  - intf: "g0/1"
    ip_address: "40.8.20.8"
    ipv6_address: "2001:40:8:20::8/64"
    mask: "255.255.255.0"    
    state: "up" 
  - intf: "loopback0"
    ip_address: "8.8.8.8"
    ipv6_address: "2001::8:8:8:8/128"
    mask: "255.255.255.255"
    state: "up"