---

interfaces:
  - intf: "g0/0"
    ip_address: "20.5.6.5"
    ipv6_address: "2001:20:5:6::5/64"
    mask: "255.255.255.0"
    state: "up" 
  - intf: "g0/1"
    ip_address: "20.4.5.5"
    ipv6_address: "2001:20:4:5::5/64"
    mask: "255.255.255.0"
    state: "up"
  - intf: "g0/2"
    ip_address: "20.5.19.5"
    ipv6_address: "2001:20:5:19::5/64"
    mask: "255.255.255.0"
    state: "up"
  - intf: "loopback0"
    ip_address: "5.5.5.5"
    ipv6_address: "2001::5:5:5:5/128"
    mask: "255.255.255.255"
    state: "up"

ospf:
  process_id: "100"
  router_id: "5.5.5.5"
  networks:
    - subnet: "20.5.6.0"
      intf: "g0/0"
      mask: "0.0.0.255"      
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - subnet: "20.4.5.0"
      intf: "g0/1"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - subnet: "20.5.19.0"
      intf: "g0/2"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: "point-to-point"
      authentication_type: "md5"
      authentication_key: "INEMD5"
    - subnet: "5.5.5.5"
      intf: "loopback0"
      mask: "0.0.0.0"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""