---

interfaces:
  - intf: "g0/0"
    ip_address: "10.1.2.2"
    mask: "255.255.255.0"
    state: "up" 
  - intf: "g0/1"
    ip_address: "20.2.3.2"
    mask: "255.255.255.0"
    state: "up"
  - intf: "loopback0"
    ip_address: "2.2.2.2"
    mask: "255.255.255.255"
    state: "up"

ospf:
  process_id: "100"
  router_id: "2.2.2.2"
  networks:
    - subnet: "10.1.2.0"
      intf: "g0/0"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - subnet: "20.2.3.0"
      intf: "g0/1"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""
    - subnet: "2.2.2.2"
      intf: "loopback0"
      mask: "0.0.0.0"
      area: "0"
      cost: ""
      network_type: ""
      authentication_type: ""
      authentication_key: ""