---

- name: "PLAY 1 - CONFIGURE IOS INTERFACES"
  hosts: all_ios_network
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "configure interfaces"
      cisco.ios.ios_config:
        src: "base/interface_config_ios.j2"

- name: "PLAY 2 - CONFIGURE XR INTERFACES"
  hosts: xr_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "configure interfaces xr routers"
      cisco.iosxr.iosxr_config:
        src: "base/interface_config_xr.j2"