---

- name: "PLAYBOOK TO GET SHOW VERSION OF IOS DEVICES"
  hosts: ios_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "run show version command"
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: output
    - debug: var=output.stdout_lines