---

- name: "PLAY 1 - CONFIGURE ISIS NETWORK TYPES - IOS"
  hosts: ios_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "Configure ISIS Network Type"
      cisco.ios.ios_config:
        src: "isis/task_2.12_isis_network_types_ios.j2"
        save_when: "always"

      register: output

    - name: "Show configurations"
      debug: var=output

- name: "PLAY 2 - CONFIGURE ISIS NETWORK TYPES - XR"
  hosts: xr_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "Configure ISIS Network Types"
      cisco.iosxr.iosxr_config:
        src: "isis/task_2.12_isis_network_types_xr.j2"

      register: output

    - name: "Show Configurations"
      debug: var=output
  