---

- name: "PLAY 1 - CONFIGURE ISIS ROUTE LEAKING IOS ROUTERS"
  hosts: ios_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "configure isis route leaking"
      cisco.ios.ios_config:
        src: "isis/task_2.17_isis_route_leaking_ios.j2"


- name: "PLAY 2 - CONFIGURE ISIS ROUTE LEAKING IOS XR ROUTERS"
  hosts: "10.10.100.19"
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "configure prefix set"
      cisco.iosxr.iosxr_config:
        src: "isis/task_2.17_isis_route_leaking_xr.j2"