---

- name: "Play 1 - Configure MPLS Tunnels - IOS"
  hosts: edge_ios
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Configure BGP on Edge IOS Routers"
      cisco.ios.ios_config:
        src: "vpn/all_tasks_bgp_ios.j2"
        save_when: "changed"
      register: output
    
    - name: "Print configurations"
      debug: var=output

    - name: "Configure L3VPN for Customer Routing IOS Routers"
      cisco.ios.ios_config:
        src: "vpn/l3vpn_customer_routing_ios.j2"
      register: output
      
    - name: "Print configurations"
      debug: var=output

- name: "PLAY 2 - Configure MPLS Tunnels - XR"
  hosts: edge_xr
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Configure BGP on Edge XR Routers"
      cisco.iosxr.iosxr_config:
        src: "vpn/all_tasks_bgp_xr.j2"
      register: output

    - name: "Print Configurations"
      debug: var=output
    
    - name: "Configure L3VPN for Customer Routing"
      cisco.iosxr.iosxr_config:
        src: "vpn/l3vpn_customer_routing_xr.j2"
      register: output

    - name: "Print configurations"
      debug: var=output