---

- name: "PLAY 1 - MULTI TOPOLOGY ISIS IOS ROUTERS"
  hosts: ios_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "Configure Multi Topology ISIS"
      cisco.ios.ios_config:
        src: "isis/task_2.19_isis_multitopology_ios.j2"


- name: "PLAY 2 - MULTI TOPOLOGY ISIS XR ROUTERS"
  hosts: xr_routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: "Configure Multi Topology ISIS"
      cisco.iosxr.iosxr_config:
        src: "isis/task_2.19_isis_multitopology_xr.j2"