mpls:
  protocol: "ldp"
  router_id: "loopback0"
  password_required: True
  interfaces:
    - intf: "g0/0"
    - intf: "g0/1"
    - intf: "g0/2"
  autoconfig:
    - igp: "ospf"
      process_id: "100"
      enable: False
    - igp: "isis"
      process_id: ""
      enable: True
  neighbors: ""
  group_acl: ""    
  option_1: ""
  fallback:
    password: "R5PASS"