---

l3vpns:
  - vrf: "VPN_A"
    rd: "100:1"
    address_families:
      - family: "ipv4"
        rt_import:
          - "100:1"
        rt_export:
          - "100:1"
    interfaces:
      - intf: "g0/4"
        ipv4_add: "10.5.8.5"
        mask: "255.255.255.0"
    routing:
      type: "eigrp"
      as: "1"
      metric: "10"
      networks:
        - subnet: "10.5.8.0"
          mask: "0.0.0.255"